name: Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: '1.15'
    - run: go build -o myapp ./main.go
    - uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: myapp
